### ISSUE TITLE
Useful for Rhasspy 2.5.11 docker? Sound device in /dev/snd/ ?

### ISSUE THREAD

**Issue by pipsen** [ich777/unraid-sound-driver#5]
Hello,

I am migrating from my Synology to an Unraid based Docker Server. I migrated now all of them - just one is missing: Rhasspy!

In my synology kernel I have my connected USB microphone and speaker in /dev/snd and route this in my Rhasspy docker contaier -> works like a charm.

Unfortunately, the /dev/snd folder in Unraid is empty and the docker container does not detect my microphone and speaker :-(

I installed your package, but this did not help. Could my maybe help me?

Thank you very much!

**Comment by ich777** [comment]
Please provide your Diagnostics or ehat kind of sound hardware that you have.

Please note that this plugin is nowadays mainly designed to support USB sound devices.

**Comment by pipsen** [comment]
I have two different devices:
- Jabra Speak 410 (USB)
- Jabra Speak 510 (USB)
- Razer Seiren mini (USB)

`
services:
  rhasspy:
    image: rhasspy/rhasspy
    container_name: rhasspy
    network_mode: bridge
    restart: always
    ports:
      - 12101:12101
      - 12183:12183
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - /mnt/cache/appdata/rhasspy:/profiles
      - /etc/localtime:/etc/localtime:ro
    command: --profile de --user-profiles /profiles
`
What do I have to put into "devices" section of my compose file?

**Comment by ich777** [comment]
I think you have to use /dev/usb but I‘m not sure about that since I don‘t know and use that container nor the sound-driver anymore.

I know for sure that the driver is working for others but I don‘t know how they use the plugin and with which containers, sorry…

**Comment by pipsen** [comment]
How is the installation process? I copied the tgz file to /boot/config/extra/ and rebooted, but I dont see the extracted files

**Comment by ich777** [comment]
This is definitely wrong.
Please remove the tgz file from /boot/extra

Go to your Plugin page within Unraid, click on the tab Install Plugin, paste that: `https://raw.githubusercontent.com/ich777/unraid-sound-driver/master/sound-driver.plg` in the text field, click Install and wait for the Done button to appear, after that reboot.

**Comment by pipsen** [comment]
Oh my god, it is just working plug and play and Rhasspy is working! Thank you! Thank you! Thank you!

**Comment by ich777** [comment]
Glad to hear that it’s working. I‘ll close this issue.
